lexer =
  rules: [
    ["[a-zA-Z_-][a-zA-Z0-9_-]*",                       "return 'IDENTIFIER';"]
    ["(\"[^\"]*\"|'[^']*')",                           "return 'STRING';"]
    ["#([0-9a-fA-F]+)\\b",                             "return 'HEXNUMBER'"]
    ["-?\\d+(\\.\\d+)?(%|in|cm|mm|em|ex|pt|pc|px)\\b", "return 'UNITNUMBER'"]
    ["-?\\.\\d+(%|in|cm|mm|em|ex|pt|pc|px)\\b",        "return 'UNITNUMBER'"]
    ["-?\\d+(\\.\\d+)?",                               "return 'NUMBER'"]
    ["-?\\.\\d+",                                      "return 'NUMBER'"]
    ["\\s+",                                           "/* skip whitespaces */"]
    ["/\\*.*?\\*/",                                    "/* skip comments */"]
    ["\\@",                                            "return '@';"]
    ["\\$",                                            "return '$';"]
    ["\\+",                                            "return '+';"]
    ["\\{",                                            "return '{';"]
    ["\\}",                                            "return '}';"]
    ["\\(",                                            "return '(';"]
    ["\\)",                                            "return ')';"]
    ["\\[",                                            "return '[';"]
    ["\\]",                                            "return ']';"]
    ["\\<",                                            "return '<';"]
    ["\\>",                                            "return '>';"]
    ["\\^",                                            "return '^';"]
    ["\\~",                                            "return '~';"]
    ["=",                                              "return '=';"]
    ["\\-",                                            "return '-';"]
    ["\\|",                                            "return '|';"]
    ["\\#",                                            "return '#';"]
    ["\\.",                                            "return '.';"]
    ["::",                                             "return '::';"]
    [":",                                              "return ':';"]
    [";",                                              "return ';';"]
    ["\\*",                                            "return '*';"]
    ["\\\\",                                           "return '\';"]
    ["/",                                              "return '/';"]
    [",",                                              "return ',';"]
  ]

module.exports = lexer
